05/31/20 02:18:21 (pid:23227) '/usr/bin/docker info' did not exit successfully (code 256); the first line of output was 'Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied'.
05/31/20 02:18:22 (pid:23227) FILETRANSFER: "/wntmp/condor/execute/dir_13591/glide_6W0T19/main/condor/libexec/curl_plugin -classad" did not produce any output, ignoring
05/31/20 02:18:22 (pid:23227) FILETRANSFER: failed to add plugin "/wntmp/condor/execute/dir_13591/glide_6W0T19/main/condor/libexec/curl_plugin" because: FILETRANSFER:1:"/wntmp/condor/execute/dir_13591/glide_6W0T19/main/condor/libexec/curl_plugin -classad" did not produce any output, ignoring
05/31/20 02:18:22 (pid:23227) WARNING: Initializing plugins returned: FILETRANSFER:1:"/wntmp/condor/execute/dir_13591/glide_6W0T19/main/condor/libexec/curl_plugin -classad" does not support any methods, ignoring|FILETRANSFER:1:"/wntmp/condor/execute/dir_13591/glide_6W0T19/main/condor/libexec/curl_plugin -classad" did not produce any output, ignoring
